import { StyleSheet } from 'react-native';

export const voiceScreenStyles = StyleSheet.create({
  backgroundBlob1: {
    position: 'absolute',
    top: '-20%',
    left: '-10%',
    width: 600,
    height: 600,
    borderRadius: 300,
    opacity: 0.5,
  },
  backgroundBlob2: {
    position: 'absolute',
    bottom: '10%',
    right: '-10%',
    width: 500,
    height: 500,
    borderRadius: 250,
    opacity: 0.5,
  },
  headerContainer: {
    width: '100%',
    alignItems: 'center',
  },
  liveSessionBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 9999,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    overflow: 'hidden',
  },
  liveDotContainer: {
    position: 'relative',
    width: 8,
    height: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pingDot: {
    position: 'absolute',
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#19b3e6',
  },
  liveDot: {
    position: 'absolute',
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#19b3e6',
  },
  liveSessionText: {
    fontSize: 12,
    fontWeight: '500',
    letterSpacing: 0.5,
    color: 'rgba(209, 213, 219, 1)',
    textTransform: 'uppercase',
  },
  listeningText: {
    marginTop: 16,
    fontSize: 24,
    fontWeight: '300',
    letterSpacing: 0.5,
    color: 'rgba(255, 255, 255, 0.9)',
    textAlign: 'center',
  },
  recordingDuration: {
    marginTop: 8,
    fontSize: 14,
    fontWeight: '500',
    color: 'rgba(255, 255, 255, 0.7)',
    textAlign: 'center',
  },
  durationWarning: {
    color: '#f87171',
    fontWeight: '600',
  },
  rippleContainer: {
    position: 'absolute',
    width: 192,
    height: 192,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ripple: {
    position: 'absolute',
    width: 192,
    height: 192,
    borderRadius: 96,
    borderWidth: 1,
  },
  innerGlow: {
    position: 'absolute',
    width: 256,
    height: 256,
    borderRadius: 128,
    top: -32,
    left: -32,
  },
  blob: {
    width: 256,
    height: 256,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    shadowColor: '#19b3e6',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 40,
    elevation: 10,
  },
  bottomControlsContainer: {
    position: 'relative',
    zIndex: 10,
    paddingBottom: 40,
    paddingHorizontal: 24,
    width: '100%',
  },
  bottomControlsWrapper: {
    maxWidth: 448,
    width: '100%',
    alignSelf: 'center',
  },
  glassPanel: {
    borderRadius: 9999,
    padding: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(17, 29, 33, 0.6)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.5,
    shadowRadius: 20,
    elevation: 20,
    overflow: 'hidden',
  },
  controlButton: {
    height: 56,
    width: 56,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 28,
  },
  controlButtonInner: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 28,
  },
  visualizerContainer: {
    flex: 1,
    height: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    marginHorizontal: 16,
    opacity: 0.5,
    borderRadius: 9999,
  },
  visualizerBar: {
    width: 4,
    backgroundColor: '#19b3e6',
    borderRadius: 2,
    minHeight: 12,
  },
  endButton: {
    height: 56,
    width: 56,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 28,
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.2)',
  },
  endButtonInner: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 28,
  },
  interfaceLabel: {
    textAlign: 'center',
    color: 'rgba(255, 255, 255, 0.2)',
    fontSize: 10,
    fontWeight: '500',
    letterSpacing: 2,
    textTransform: 'uppercase',
    marginTop: 24,
  },
});
